language: objective-c
osx_image: xcode7.1

branches:
  only:
    - master

script:
  - chmod a+x ./travis/script.sh
  # This is a workaround for a Travis-CI bug where the log might get cut-off.
  # See the [Travis-CI issue #4716](https://github.com/travis-ci/travis-ci/issues/4716).
  - sleep 3

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT_NAME="TransitApp"
    - SCHEME_IOS="TransitApp-iOS"
    - BUILD="clean build"
    - BUILD_TEST="clean build test"
    - PROJECT_FRAMEWORK="TransitApp/TransitApp.xcodeproj"
  matrix:
    - TEST_SDK=iphonesimulator  TEST_DEST="platform=iOS Simulator,OS=9.1,name=iPhone 5s"   SCHEME="$SCHEME_IOS"    BUILD_ACTIONS="$BUILD_TEST" EXTRA_ARGUMENTS="$ENABLE_CODE_COVERAGE" PROJECT="$PROJECT_FRAMEWORK"
  